# Generated by Django 4.1 on 2022-08-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='toDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=144)),
                ('category_type', models.CharField(choices=[('WORK', 'WORK'), ('PERSONAL', 'PERSONAL}')], default='PERSONAL', max_length=24)),
            ],
        ),
    ]
